let map1 = [
	'                                                              ',
	'                                                              ',
	'                         l f                                  ',
	'                    Hgggggggggg                               ',
	'                    H ddddddd                                 ',
	'              ccF   H                                         ',
	'             ggggg  H                                         ',
	'              dd   gg                        ggggg            ',
	'            F        gg                       ddd             ',
	'      c    gg    gg                                     S  P  ',
	'     ggg       ggddgH       l   f l                     gg gH ',
	'    gdddg           H     ggggggggggg                 dddd dH ',
	'   gddddg      F    H    ddddddddddddg                      H ',
	'  cc    Fc     ggg  H     dddddddddddddd              ccccc H ',
	'gggg   ggggg        H                      l          gggggggg',
	'ddddgggdddddggccFcccgggggrrrrrrrrrrrrr    gggccFcccgggdddddddd',
	'ddddddddddddddggggggddddd            gggggdddggggggddddddddddd',
	'ddddddddddddddddddddddddd                  ddddddddddddddddddd',
	'ddddddddddddddddddddddddd                     dddddddddddddddd',
	'ddddddddddddddddddddddddd             dddddddddddddddddddddddd',
	'ddddddddddddddddddddddddd             dddddddddddddddddddddddd',
	'ddddddddddddddddddddddddd             dddddddddddddddddddddddd',
	'ddddddddddddddddddddddddd             dddddddddddddddddddddddd',
	'ddddddddddddddddddddddddd             dddddddddddddddddddddddd'
];